name: stream_service
version: 0.2.3
author: Vitaliy Vostrikov <rasart.pro@gmail.com>
homepage: https://github.com/Rasarts/stream_service
documentation: https://github.com/Rasarts/stream_service/wiki
description: >
  Stream Service
    - Stream for decouple many objects
    - Simple subscription on object events
    - Work both, on client and server
dev_dependencies:
  test: '^0.12.15+1'